spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  cache:
    type: redis
    redis:
      time-to-live: 3600000

server:
  compression:
    enabled: true
  http2:
    enabled: true

logging:
  level:
    root: WARN
    io.orvion: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure: include: health,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
