name: Feature request
description: Propor melhoria de produto, negócio ou operação
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Oportunidade
      description: Que dor ou oportunidade de negócio esta melhoria atende?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Critérios de sucesso
    validations:
      required: true
